name: "PodCast Generator"
author: "George"
description: "Generate Feed"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icons: "git-branch"
  color: "red"
inputs:
  email:
    description: Mail id 
    required: true
    default: ${{ github.actor}}@localhost
  name:
    description: name
    required: true
    default: ${{ github.actor}}
